@0xe7bf7188ae764e6b;

# Code generated by protoc-gen-protokit. DO NOT EDIT.
# versions:
# 	protoc-gen-protokit test
# 	protoc test
# source: buffers/wellknown.capnp
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# protokit — https://github.com/the-protobuf-project/protokit
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("buffers::wellknown");

# Timestamp is google.protobuf.Timestamp: seconds since the Unix epoch plus a
# nanosecond adjustment.
struct Timestamp @0xd4efd046929394b8 {
  seconds @0 :Int64;
  nanos @1 :Int32;
}
