@0xa95e271611526053;

# Code generated by protoc-gen-protokit. DO NOT EDIT.
# versions:
# 	protoc-gen-protokit test
# 	protoc test
# source: sensors/v1/enums.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# protokit — https://github.com/the-protobuf-project/protokit
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("sensors::v1");

# SensorKind is the physical modality a sensor measures.
#
# Narrowed to a single byte: there will never be 256 modalities, and this enum
# appears inside a reading that is published at sensor rate.
# (buffers.v1.enumeration).underlying asked for 8 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum SensorKind @0xe35dcc6c3350e113 {
  # SENSOR_KIND_UNSPECIFIED is the AIP-126 zero value. A sensor should never
  # report it; a reading carrying it means the producer did not set the field.
  unspecified @0;
  # SENSOR_KIND_LIDAR is a scanning rangefinder producing point clouds.
  lidar @1;
  # SENSOR_KIND_CAMERA is an imager producing encoded frames.
  camera @2;
  # SENSOR_KIND_IMU is an inertial unit producing three-axis measurements.
  imu @3;
  # SENSOR_KIND_WHEEL_ENCODER is an odometry source producing scalar counts.
  wheelEncoder @4;
}

# HealthState is a sensor's current operability.
# (buffers.v1.enumeration).underlying asked for 8 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum HealthState @0xfe30adc1670ee2d4 {
  # HEALTH_STATE_UNSPECIFIED is the AIP-126 zero value, meaning the health of
  # the sensor has not been assessed.
  unspecified @0;
  # HEALTH_STATE_HEALTHY means the sensor is publishing within specification.
  healthy @1;
  # HEALTH_STATE_DEGRADED means the sensor is publishing, but outside its
  # nominal rate or accuracy.
  degraded @2;
  # HEALTH_STATE_FAILED means the sensor has stopped publishing.
  failed @3;
}
