@0x917094a9a0b68e47;

# Code generated by protoc-gen-protokit. DO NOT EDIT.
# versions:
# 	protoc-gen-protokit test
# 	protoc test
# source: sensors/v1/geometry.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# protokit — https://github.com/the-protobuf-project/protokit
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("sensors::v1");

# Vector3 is a point or displacement in three dimensions.
#
# It is the canonical LAYOUT_STRUCT case: three fixed-width scalars and nothing
# else, so it can be a 24-byte inline blob in every target that has one. Making
# it a table instead would cost a vtable lookup per axis on a message that a
# perception stack reads a few million times a second.
# Declared LAYOUT_STRUCT. Cap'n Proto has no table/struct distinction —
# every struct is already a flat, fixed-offset record — so the layout option
# changes nothing here. It is honoured by the FlatBuffers target.
struct Vector3 @0xd5d233cc4d2c3c01 {
  # x is the first axis component, in metres.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  x @0 :Float64;
  # y is the second axis component, in metres.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  y @1 :Float64;
  # z is the third axis component, in metres.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  z @2 :Float64;
}

# Quaternion is an orientation in Hamilton convention.
# Declared LAYOUT_STRUCT. Cap'n Proto has no table/struct distinction —
# every struct is already a flat, fixed-offset record — so the layout option
# changes nothing here. It is honoured by the FlatBuffers target.
struct Quaternion @0xafe70c4988e319b6 {
  # x is the first vector component.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  x @0 :Float64;
  # y is the second vector component.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  y @1 :Float64;
  # z is the third vector component.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  z @2 :Float64;
  # w is the scalar component.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  w @3 :Float64;
}

# Pose is a position and an orientation together.
#
# Still a struct: a struct may contain other structs, and this one is exactly
# the two above laid end to end.
# Declared LAYOUT_STRUCT. Cap'n Proto has no table/struct distinction —
# every struct is already a flat, fixed-offset record — so the layout option
# changes nothing here. It is honoured by the FlatBuffers target.
struct Pose @0xbb241d9510d2f1e1 {
  # position is the translation component, in the parent frame.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  position @0 :Vector3;
  # orientation is the rotation component, in the parent frame.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  orientation @1 :Quaternion;
}
