@0xfcd7ab176a1c47d5;

# Code generated by protoc-gen-protokit. DO NOT EDIT.
# versions:
# 	protoc-gen-protokit test
# 	protoc test
# source: sensors/v1/sensors_service.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# protokit — https://github.com/the-protobuf-project/protokit
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("sensors::v1");

using Sensors = import "/sensors/v1/sensors.capnp";

# GetSensorRequest is the request for SensorService.GetSensor.
struct GetSensorRequest @0xdfbfb22a6b66c44e {
  # name is the sensor to return.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# ListSensorsRequest is the request for SensorService.ListSensors.
struct ListSensorsRequest @0xd2862b2e7f04f672 {
  # parent is the robot whose sensors to list.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # page_size is the maximum number of sensors to return.
  pageSize @1 :Int32;
  # page_token continues a previous call.
  pageToken @2 :Text;
}

# ListSensorsResponse is the response for SensorService.ListSensors.
struct ListSensorsResponse @0xf7e3eafb90d45ebc {
  # sensors are the sensors on the robot.
  sensors @0 :List(Sensors.Sensor);
  # next_page_token continues this call, or is empty at the end.
  nextPageToken @1 :Text;
}

# CreateSensorRequest is the request for SensorService.CreateSensor.
struct CreateSensorRequest @0x865af49cae16d637 {
  # parent is the robot to mount the sensor on.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # sensor_id is the id to give the new sensor.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  sensorId @1 :Text;
  # sensor is the sensor to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  sensor @2 :Sensors.Sensor;
}

# UpdateSensorRequest is the request for SensorService.UpdateSensor.
struct UpdateSensorRequest @0xfd9b1a92bff4f5ae {
  # sensor carries the new values and, in its name, which sensor to update.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  sensor @0 :Sensors.Sensor;
  # update_mask lists the fields to change.
  updateMask @1 :List(Text);
}

# DeleteSensorRequest is the request for SensorService.DeleteSensor.
struct DeleteSensorRequest @0xb857a1b038b8c9a6 {
  # name is the sensor to remove.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
  # force removes the sensor even when it still has readings under it.
  force @1 :Bool;
}

# StreamReadingsRequest is the request for SensorService.StreamReadings.
struct StreamReadingsRequest @0xedd34f321e069a12 {
  # name is the sensor to subscribe to.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# StreamReadingsResponse is one element of the SensorService.StreamReadings
# stream.
struct StreamReadingsResponse @0xc0d14227e83a2d2b {
  # reading is the sample the sensor produced.
  reading @0 :Sensors.Reading;
}

# SensorService manages the sensors on a fleet of robots.
#
# Its methods are ordinary AIP standard methods, which is the point: nothing in
# this file is written for the sake of the serialization targets. The Cap'n
# Proto interface, the ROS .srv pair per call, and the ROS topic for the
# streaming method are all derived from the AIP shape the service already has.
interface SensorService @0xc3eb6d08efaa3839 {
  # GetSensor returns one sensor.
  # AIP-131 standard method.
  getSensor @0 (request :GetSensorRequest) -> (response :Sensors.Sensor);

  # ListSensors returns the sensors on a robot.
  # AIP-132 standard method.
  listSensors @1 (request :ListSensorsRequest) -> (response :ListSensorsResponse);

  # CreateSensor registers a sensor on a robot.
  # AIP-133 standard method.
  createSensor @2 (request :CreateSensorRequest) -> (response :Sensors.Sensor);

  # UpdateSensor mutates a sensor.
  # AIP-134 standard method.
  updateSensor @3 (request :UpdateSensorRequest) -> (response :Sensors.Sensor);

  # DeleteSensor removes a sensor.
  # AIP-135 standard method.
  deleteSensor @4 (request :DeleteSensorRequest) -> ();

  # StreamReadings publishes every reading a sensor produces.
  #
  # Server streaming is what makes this a publication rather than a call, and
  # the plugin would classify it that way from the `stream` keyword alone. The
  # explicit transport is belt and braces; the topic name is the part nothing
  # else can supply.
  # Server streaming. Cap'n Proto RPC has no streaming return, so the stream is
  # a capability the caller supplies and the callee pushes to. Topic: "sensor_readings".
  streamReadings @5 (request :StreamReadingsRequest, sink :StreamReadingsSink) -> ();
}

# Stream sink for StreamReadings. The caller implements it; the callee calls push once
# per element and done when the stream ends. Returning from push is the
# backpressure signal: the callee should await it before pushing again.
interface StreamReadingsSink @0xda86e3afdd0bf8ad {
  push @0 (value :StreamReadingsResponse) -> ();
  done @1 () -> ();
}
