@0xd67561c09d53413a;

# Code generated by protoc-gen-protokit. DO NOT EDIT.
# versions:
# 	protoc-gen-protokit test
# 	protoc test
# source: sensors/v1/sensors.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# protokit — https://github.com/the-protobuf-project/protokit
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("sensors::v1");

using Enums = import "/sensors/v1/enums.capnp";
using Geometry = import "/sensors/v1/geometry.capnp";
using Wellknown = import "/buffers/wellknown.capnp";

# Robot is one fielded machine.
struct Robot @0xfbc6d7fc267d1431 {
  # name is the resource name, `robots/{robot}`.
  name @0 :Text;
  # display_name is the human-facing label.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  displayName @1 :Text;
  # serial is the immutable manufacturer serial.
  serial @2 :Text;
  # pose is where the robot last reported itself.
  pose @3 :Geometry.Pose;
  # labels are operator-assigned key and value tags.
  labels @4 :List(RobotLabelsEntry);
  # create_time is when the robot was registered.
  createTime @5 :Wellknown.Timestamp;

  # Entry of labels, which is a proto map. Cap'n Proto has no map type and no
  # keyed-list convention, so a list of pairs is the whole of what it can say:
  # uniqueness and lookup are the reader's responsibility.
  struct RobotLabelsEntry @0xc000e6e5da1a3b5f {
    key @0 :Text;
    value @1 :Text;
  }
}

# Sensor is one device mounted on a robot.
struct Sensor @0x9ff6b7ea0bc8e01b {
  # name is the resource name, `robots/{robot}/sensors/{sensor}`.
  name @0 :Text;
  # kind is the modality this sensor measures.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  kind @1 :Enums.SensorKind;
  # health is the sensor's current operability.
  health @2 :Enums.HealthState;
  # mount is the sensor's pose in the robot's body frame.
  mount @3 :Geometry.Pose;
  # firmware is the running firmware version.
  firmware @4 :Text;
  # proto field 6 was removed and reserved; this holds its ordinal.
  removed6 @5 :Void;
  # rate_hz is the nominal publication rate.
  rateHz @6 :Float32;
}

# Reading is one sample published by a sensor.
#
# The payload oneof is the interesting shape: proto's oneof is a Cap'n Proto
# union almost exactly, and a FlatBuffers union with a wrapper table per scalar
# arm, since FlatBuffers unions may only hold tables.
struct Reading @0x8333064359168264 {
  # name is the resource name.
  name @0 :Text;
  # observe_time is when the sample was taken, not when it was received.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  observeTime @1 :Wellknown.Timestamp;
  # sequence is the publisher's monotonic counter, used to detect drops.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  sequence @2 :Int64;
  # payload is the sample itself, whose shape depends on the sensor's modality.
  payload :union {
    # scalar is a single measurement, for an encoder or a thermometer.
    scalar @3 :Float64;
    # vector is a three-axis measurement, for an inertial unit.
    vector @4 :Geometry.Vector3;
    # cloud is a point cloud, for a rangefinder.
    cloud @5 :PointCloud;
    # frame is an encoded image, for a camera.
    frame @6 :ImageFrame;
  }
}

# PointCloud is an unstructured set of returns.
struct PointCloud @0xdfda71e77999068d {
  # points are the returns in the sensor frame.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  points @0 :List(Geometry.Vector3);
  # intensities are per-point return strengths, parallel to points.
  intensities @1 :List(Float32);
}

# ImageFrame is one encoded image.
struct ImageFrame @0xb318247e96ac1799 {
  # width is the frame width in pixels.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  width @0 :Int32;
  # height is the frame height in pixels.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  height @1 :Int32;
  # encoding names the pixel format, for example "rgb8".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  encoding @2 :Text;
  # data is the encoded payload.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  data @3 :Data;
}
