// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: buffers/v1/annotations.proto

package bufferspbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_buffers_v1_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*FileOptions)(nil),
		Field:         53000,
		Name:          "buffers.v1.file",
		Tag:           "bytes,53000,opt,name=file",
		Filename:      "buffers/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOptions)(nil),
		Field:         53001,
		Name:          "buffers.v1.message",
		Tag:           "bytes,53001,opt,name=message",
		Filename:      "buffers/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         53002,
		Name:          "buffers.v1.field",
		Tag:           "bytes,53002,opt,name=field",
		Filename:      "buffers/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*EnumOptions)(nil),
		Field:         53003,
		Name:          "buffers.v1.enumeration",
		Tag:           "bytes,53003,opt,name=enumeration",
		Filename:      "buffers/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*EnumValueOptions)(nil),
		Field:         53004,
		Name:          "buffers.v1.enum_value",
		Tag:           "bytes,53004,opt,name=enum_value",
		Filename:      "buffers/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: (*OneofOptions)(nil),
		Field:         53005,
		Name:          "buffers.v1.oneof",
		Tag:           "bytes,53005,opt,name=oneof",
		Filename:      "buffers/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceOptions)(nil),
		Field:         53006,
		Name:          "buffers.v1.service",
		Tag:           "bytes,53006,opt,name=service",
		Filename:      "buffers/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodOptions)(nil),
		Field:         53007,
		Name:          "buffers.v1.method",
		Tag:           "bytes,53007,opt,name=method",
		Filename:      "buffers/v1/annotations.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// file names the per-file things each target needs: the FlatBuffers namespace
	// and identifier, the Cap'n Proto file ID, the ROS package, the JVM package.
	//
	// optional buffers.v1.FileOptions file = 53000;
	E_File = &file_buffers_v1_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// message shapes the record: table or struct, its Cap'n Proto ID, the targets
	// it belongs to.
	//
	// optional buffers.v1.MessageOptions message = 53001;
	E_Message = &file_buffers_v1_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// field shapes the field: its ordinal, its ROS bounds and default, its
	// FlatBuffers key/shared attributes, its Cap'n Proto group.
	//
	// optional buffers.v1.FieldOptions field = 53002;
	E_Field = &file_buffers_v1_annotations_proto_extTypes[2]
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// enumeration shapes the enum: its underlying integer width and whether it is a
	// bitmask.
	//
	// Named `enumeration` rather than `enum` because `enum` is a reserved word in
	// several of the languages these options are compiled into — including C++ and
	// Java, where the generated accessor would not compile.
	//
	// optional buffers.v1.EnumOptions enumeration = 53003;
	E_Enumeration = &file_buffers_v1_annotations_proto_extTypes[3]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// enum_value pins one enumerant's Cap'n Proto ordinal.
	//
	// optional buffers.v1.EnumValueOptions enum_value = 53004;
	E_EnumValue = &file_buffers_v1_annotations_proto_extTypes[4]
)

// Extension fields to descriptorpb.OneofOptions.
var (
	// oneof names the union the oneof becomes in targets that have one.
	//
	// optional buffers.v1.OneofOptions oneof = 53005;
	E_Oneof = &file_buffers_v1_annotations_proto_extTypes[5]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// service shapes the call surface: whether an interface is emitted, its
	// Cap'n Proto ID, whether ROS services are generated.
	//
	// optional buffers.v1.ServiceOptions service = 53006;
	E_Service = &file_buffers_v1_annotations_proto_extTypes[6]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// method shapes one call: its ordinal, its transport, its topic name.
	//
	// optional buffers.v1.MethodOptions method = 53007;
	E_Method = &file_buffers_v1_annotations_proto_extTypes[7]
)

var File_buffers_v1_annotations_proto protoreflect.FileDescriptor

const file_buffers_v1_annotations_proto_rawDesc = "" +
	"\n" +
	"\x1cbuffers/v1/annotations.proto\x12\n" +
	"buffers.v1\x1a\x14buffers/v1/rpc.proto\x1a\x17buffers/v1/schema.proto\x1a google/protobuf/descriptor.proto:K\n" +
	"\x04file\x12\x1c.google.protobuf.FileOptions\x18\x88\x9e\x03 \x01(\v2\x17.buffers.v1.FileOptionsR\x04file:W\n" +
	"\amessage\x12\x1f.google.protobuf.MessageOptions\x18\x89\x9e\x03 \x01(\v2\x1a.buffers.v1.MessageOptionsR\amessage:O\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\x8a\x9e\x03 \x01(\v2\x18.buffers.v1.FieldOptionsR\x05field:Y\n" +
	"\venumeration\x12\x1c.google.protobuf.EnumOptions\x18\x8b\x9e\x03 \x01(\v2\x17.buffers.v1.EnumOptionsR\venumeration:`\n" +
	"\n" +
	"enum_value\x12!.google.protobuf.EnumValueOptions\x18\x8c\x9e\x03 \x01(\v2\x1c.buffers.v1.EnumValueOptionsR\tenumValue:O\n" +
	"\x05oneof\x12\x1d.google.protobuf.OneofOptions\x18\x8d\x9e\x03 \x01(\v2\x18.buffers.v1.OneofOptionsR\x05oneof:W\n" +
	"\aservice\x12\x1f.google.protobuf.ServiceOptions\x18\x8e\x9e\x03 \x01(\v2\x1a.buffers.v1.ServiceOptionsR\aservice:S\n" +
	"\x06method\x12\x1e.google.protobuf.MethodOptions\x18\x8f\x9e\x03 \x01(\v2\x19.buffers.v1.MethodOptionsR\x06methodBo\n" +
	"\x0ecom.buffers.v1B\x10AnnotationsProtoP\x01ZIgithub.com/the-protobuf-project/buffers/plugin/pb/bufferspbv1;bufferspbv1b\x06proto3"

var file_buffers_v1_annotations_proto_goTypes = []any{
	(*descriptorpb.FileOptions)(nil),      // 0: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil),   // 1: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),     // 2: google.protobuf.FieldOptions
	(*descriptorpb.EnumOptions)(nil),      // 3: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil), // 4: google.protobuf.EnumValueOptions
	(*descriptorpb.OneofOptions)(nil),     // 5: google.protobuf.OneofOptions
	(*descriptorpb.ServiceOptions)(nil),   // 6: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),    // 7: google.protobuf.MethodOptions
	(*FileOptions)(nil),                   // 8: buffers.v1.FileOptions
	(*MessageOptions)(nil),                // 9: buffers.v1.MessageOptions
	(*FieldOptions)(nil),                  // 10: buffers.v1.FieldOptions
	(*EnumOptions)(nil),                   // 11: buffers.v1.EnumOptions
	(*EnumValueOptions)(nil),              // 12: buffers.v1.EnumValueOptions
	(*OneofOptions)(nil),                  // 13: buffers.v1.OneofOptions
	(*ServiceOptions)(nil),                // 14: buffers.v1.ServiceOptions
	(*MethodOptions)(nil),                 // 15: buffers.v1.MethodOptions
}
var file_buffers_v1_annotations_proto_depIdxs = []int32{
	0,  // 0: buffers.v1.file:extendee -> google.protobuf.FileOptions
	1,  // 1: buffers.v1.message:extendee -> google.protobuf.MessageOptions
	2,  // 2: buffers.v1.field:extendee -> google.protobuf.FieldOptions
	3,  // 3: buffers.v1.enumeration:extendee -> google.protobuf.EnumOptions
	4,  // 4: buffers.v1.enum_value:extendee -> google.protobuf.EnumValueOptions
	5,  // 5: buffers.v1.oneof:extendee -> google.protobuf.OneofOptions
	6,  // 6: buffers.v1.service:extendee -> google.protobuf.ServiceOptions
	7,  // 7: buffers.v1.method:extendee -> google.protobuf.MethodOptions
	8,  // 8: buffers.v1.file:type_name -> buffers.v1.FileOptions
	9,  // 9: buffers.v1.message:type_name -> buffers.v1.MessageOptions
	10, // 10: buffers.v1.field:type_name -> buffers.v1.FieldOptions
	11, // 11: buffers.v1.enumeration:type_name -> buffers.v1.EnumOptions
	12, // 12: buffers.v1.enum_value:type_name -> buffers.v1.EnumValueOptions
	13, // 13: buffers.v1.oneof:type_name -> buffers.v1.OneofOptions
	14, // 14: buffers.v1.service:type_name -> buffers.v1.ServiceOptions
	15, // 15: buffers.v1.method:type_name -> buffers.v1.MethodOptions
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	8,  // [8:16] is the sub-list for extension type_name
	0,  // [0:8] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_buffers_v1_annotations_proto_init() }
func file_buffers_v1_annotations_proto_init() {
	if File_buffers_v1_annotations_proto != nil {
		return
	}
	file_buffers_v1_rpc_proto_init()
	file_buffers_v1_schema_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_buffers_v1_annotations_proto_rawDesc), len(file_buffers_v1_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 8,
			NumServices:   0,
		},
		GoTypes:           file_buffers_v1_annotations_proto_goTypes,
		DependencyIndexes: file_buffers_v1_annotations_proto_depIdxs,
		ExtensionInfos:    file_buffers_v1_annotations_proto_extTypes,
	}.Build()
	File_buffers_v1_annotations_proto = out.File
	file_buffers_v1_annotations_proto_goTypes = nil
	file_buffers_v1_annotations_proto_depIdxs = nil
}
