// rpc.proto covers the call surface: Cap'n Proto interfaces, ROS services and
// actions, and Wire's gRPC client roles.
//
// The shape of that surface is mostly not declared here. It is read from the AIP
// annotations the service already carries — google.api.http, method_signature,
// and the AIP-131 through AIP-136 naming rules — because a service that is
// already a well-formed AIP service has said everything a generator needs, and
// asking the author to restate it in a second vocabulary is how the two drift
// apart. What remains here is the handful of facts AIP genuinely does not
// express: the ordinal a Cap'n Proto method is pinned to, and whether a
// long-running method should become a ROS action rather than a service call.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: buffers/v1/rpc.proto

package bufferspbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transport names how a method's messages move, where the target distinguishes
// between a call and a stream.
//
// ROS is the target that cares: a request and response pair is a service, a
// fire-and-forget stream is a topic, and a long-running call with feedback is an
// action. Cap'n Proto reads it too, to decide whether a method returns a value
// or a stream capability.
type Transport int32

const (
	// TRANSPORT_UNSPECIFIED lets the plugin classify from the method's own shape:
	// a server-streaming method becomes a topic, an AIP-151 long-running method
	// becomes an action, and everything else becomes a call.
	Transport_TRANSPORT_UNSPECIFIED Transport = 0
	// TRANSPORT_CALL is a request and response pair — a ROS service, a Cap'n Proto
	// method returning results.
	Transport_TRANSPORT_CALL Transport = 1
	// TRANSPORT_TOPIC is a one-way publication. The method's output message is the
	// topic payload; its input is ignored, and the plugin warns when that input is
	// not the empty message, because a topic has nowhere to put it.
	Transport_TRANSPORT_TOPIC Transport = 2
	// TRANSPORT_ACTION is a goal, feedback and result triple — a ROS action. The
	// method must be AIP-151 long-running, returning google.longrunning.Operation,
	// for the three payloads to be derivable; the plugin errors naming the method
	// otherwise.
	Transport_TRANSPORT_ACTION Transport = 3
)

// Enum value maps for Transport.
var (
	Transport_name = map[int32]string{
		0: "TRANSPORT_UNSPECIFIED",
		1: "TRANSPORT_CALL",
		2: "TRANSPORT_TOPIC",
		3: "TRANSPORT_ACTION",
	}
	Transport_value = map[string]int32{
		"TRANSPORT_UNSPECIFIED": 0,
		"TRANSPORT_CALL":        1,
		"TRANSPORT_TOPIC":       2,
		"TRANSPORT_ACTION":      3,
	}
)

func (x Transport) Enum() *Transport {
	p := new(Transport)
	*p = x
	return p
}

func (x Transport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Transport) Descriptor() protoreflect.EnumDescriptor {
	return file_buffers_v1_rpc_proto_enumTypes[0].Descriptor()
}

func (Transport) Type() protoreflect.EnumType {
	return &file_buffers_v1_rpc_proto_enumTypes[0]
}

func (x Transport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Transport.Descriptor instead.
func (Transport) EnumDescriptor() ([]byte, []int) {
	return file_buffers_v1_rpc_proto_rawDescGZIP(), []int{0}
}

// ServiceOptions shapes how one service lands in each target.
type ServiceOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// skip excludes the service from every target.
	Skip bool `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	// capnp_interface controls whether a Cap'n Proto `interface` is emitted.
	//
	// Optional rather than a bare bool because the default is not a constant: a
	// service with methods becomes an interface, and one with none does not. A
	// bare bool would make "false" and "unset" indistinguishable, so a service
	// could not opt out.
	CapnpInterface *bool `protobuf:"varint,2,opt,name=capnp_interface,json=capnpInterface,proto3,oneof" json:"capnp_interface,omitempty"`
	// capnp_id pins the interface's Cap'n Proto ID. Derived from the file ID and
	// the service's fully qualified name when unset. See
	// buffers.v1.FileOptions.capnp_id on why a valid ID reads as negative.
	CapnpId int64 `protobuf:"varint,3,opt,name=capnp_id,json=capnpId,proto3" json:"capnp_id,omitempty"`
	// ros_service controls whether .srv files are emitted for the service's
	// methods. Defaults to true for a service whose methods classify as AIP
	// standard methods, since those have a request and response shape ROS can
	// express, and false otherwise.
	RosService *bool `protobuf:"varint,4,opt,name=ros_service,json=rosService,proto3,oneof" json:"ros_service,omitempty"`
	// targets restricts the service to the named targets. See
	// buffers.v1.MessageOptions.targets.
	Targets       []string `protobuf:"bytes,5,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceOptions) Reset() {
	*x = ServiceOptions{}
	mi := &file_buffers_v1_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceOptions) ProtoMessage() {}

func (x *ServiceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_buffers_v1_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceOptions.ProtoReflect.Descriptor instead.
func (*ServiceOptions) Descriptor() ([]byte, []int) {
	return file_buffers_v1_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceOptions) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *ServiceOptions) GetCapnpInterface() bool {
	if x != nil && x.CapnpInterface != nil {
		return *x.CapnpInterface
	}
	return false
}

func (x *ServiceOptions) GetCapnpId() int64 {
	if x != nil {
		return x.CapnpId
	}
	return 0
}

func (x *ServiceOptions) GetRosService() bool {
	if x != nil && x.RosService != nil {
		return *x.RosService
	}
	return false
}

func (x *ServiceOptions) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

// MethodOptions shapes how one method lands in each target.
type MethodOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// skip excludes the method. It permanently consumes its Cap'n Proto ordinal,
	// for the same reason buffers.v1.FieldOptions.skip does.
	Skip bool `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	// ordinal pins the Cap'n Proto method ordinal, 0-based within the interface.
	//
	// Leave it unset. Derivation orders methods by declaration order and records
	// the result in buffers.lock, so a method inserted in the middle of a service
	// is caught as drift rather than silently renumbering every method after it.
	Ordinal int32 `protobuf:"varint,2,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	// transport selects the call shape. See Transport.
	Transport Transport `protobuf:"varint,3,opt,name=transport,proto3,enum=buffers.v1.Transport" json:"transport,omitempty"`
	// topic overrides the ROS topic name for a TRANSPORT_TOPIC method, which
	// otherwise derives from the method name in snake_case. It is also the name an
	// eCAL publisher and subscriber pair will be generated against.
	Topic string `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	// ros_type overrides the emitted .srv or .action base name, which is otherwise
	// the method name.
	RosType string `protobuf:"bytes,5,opt,name=ros_type,json=rosType,proto3" json:"ros_type,omitempty"`
	// targets restricts the method to the named targets. See
	// buffers.v1.MessageOptions.targets.
	Targets       []string `protobuf:"bytes,6,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodOptions) Reset() {
	*x = MethodOptions{}
	mi := &file_buffers_v1_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodOptions) ProtoMessage() {}

func (x *MethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_buffers_v1_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodOptions.ProtoReflect.Descriptor instead.
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return file_buffers_v1_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *MethodOptions) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *MethodOptions) GetOrdinal() int32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *MethodOptions) GetTransport() Transport {
	if x != nil {
		return x.Transport
	}
	return Transport_TRANSPORT_UNSPECIFIED
}

func (x *MethodOptions) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *MethodOptions) GetRosType() string {
	if x != nil {
		return x.RosType
	}
	return ""
}

func (x *MethodOptions) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

var File_buffers_v1_rpc_proto protoreflect.FileDescriptor

const file_buffers_v1_rpc_proto_rawDesc = "" +
	"\n" +
	"\x14buffers/v1/rpc.proto\x12\n" +
	"buffers.v1\"\xd1\x01\n" +
	"\x0eServiceOptions\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\bR\x04skip\x12,\n" +
	"\x0fcapnp_interface\x18\x02 \x01(\bH\x00R\x0ecapnpInterface\x88\x01\x01\x12\x19\n" +
	"\bcapnp_id\x18\x03 \x01(\x03R\acapnpId\x12$\n" +
	"\vros_service\x18\x04 \x01(\bH\x01R\n" +
	"rosService\x88\x01\x01\x12\x18\n" +
	"\atargets\x18\x05 \x03(\tR\atargetsB\x12\n" +
	"\x10_capnp_interfaceB\x0e\n" +
	"\f_ros_service\"\xbd\x01\n" +
	"\rMethodOptions\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\bR\x04skip\x12\x18\n" +
	"\aordinal\x18\x02 \x01(\x05R\aordinal\x123\n" +
	"\ttransport\x18\x03 \x01(\x0e2\x15.buffers.v1.TransportR\ttransport\x12\x14\n" +
	"\x05topic\x18\x04 \x01(\tR\x05topic\x12\x19\n" +
	"\bros_type\x18\x05 \x01(\tR\arosType\x12\x18\n" +
	"\atargets\x18\x06 \x03(\tR\atargets*e\n" +
	"\tTransport\x12\x19\n" +
	"\x15TRANSPORT_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eTRANSPORT_CALL\x10\x01\x12\x13\n" +
	"\x0fTRANSPORT_TOPIC\x10\x02\x12\x14\n" +
	"\x10TRANSPORT_ACTION\x10\x03Bg\n" +
	"\x0ecom.buffers.v1B\bRpcProtoP\x01ZIgithub.com/the-protobuf-project/buffers/plugin/pb/bufferspbv1;bufferspbv1b\x06proto3"

var (
	file_buffers_v1_rpc_proto_rawDescOnce sync.Once
	file_buffers_v1_rpc_proto_rawDescData []byte
)

func file_buffers_v1_rpc_proto_rawDescGZIP() []byte {
	file_buffers_v1_rpc_proto_rawDescOnce.Do(func() {
		file_buffers_v1_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_buffers_v1_rpc_proto_rawDesc), len(file_buffers_v1_rpc_proto_rawDesc)))
	})
	return file_buffers_v1_rpc_proto_rawDescData
}

var file_buffers_v1_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_buffers_v1_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_buffers_v1_rpc_proto_goTypes = []any{
	(Transport)(0),         // 0: buffers.v1.Transport
	(*ServiceOptions)(nil), // 1: buffers.v1.ServiceOptions
	(*MethodOptions)(nil),  // 2: buffers.v1.MethodOptions
}
var file_buffers_v1_rpc_proto_depIdxs = []int32{
	0, // 0: buffers.v1.MethodOptions.transport:type_name -> buffers.v1.Transport
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_buffers_v1_rpc_proto_init() }
func file_buffers_v1_rpc_proto_init() {
	if File_buffers_v1_rpc_proto != nil {
		return
	}
	file_buffers_v1_rpc_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_buffers_v1_rpc_proto_rawDesc), len(file_buffers_v1_rpc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_buffers_v1_rpc_proto_goTypes,
		DependencyIndexes: file_buffers_v1_rpc_proto_depIdxs,
		EnumInfos:         file_buffers_v1_rpc_proto_enumTypes,
		MessageInfos:      file_buffers_v1_rpc_proto_msgTypes,
	}.Build()
	File_buffers_v1_rpc_proto = out.File
	file_buffers_v1_rpc_proto_goTypes = nil
	file_buffers_v1_rpc_proto_depIdxs = nil
}
