// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: buffers/v1/schema.proto

package bufferspbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Layout selects how a message is laid out in a target that distinguishes
// between an evolvable record and a packed one.
//
// It matters in exactly one target today — FlatBuffers, where a `table` carries
// a vtable and tolerates added and removed fields, while a `struct` is a
// fixed-size inline blob with no vtable, no defaults, and no evolution. The
// distinction is the difference between a 40-byte pose that memcpy's out of a
// shared-memory segment and one that costs a vtable indirection per field, which
// is why a robotics payload cares.
//
// It is declared here rather than in a FlatBuffers-specific option because the
// same statement — this record is fixed-shape and I am trading evolution for
// density — is the one Cap'n Proto reads to decide a field belongs in the data
// section rather than the pointer section.
type Layout int32

const (
	// LAYOUT_UNSPECIFIED means LAYOUT_TABLE.
	//
	// The default is not inferred from the message's shape, and deliberately so. A
	// message of three doubles is struct-eligible; adding a string to it is an
	// ordinary, wire-compatible proto change. If the layout were inferred, that
	// edit would silently flip the message from a packed struct to a vtable-backed
	// table — which *is* a breaking change in FlatBuffers — and nothing would say
	// so. Packing is a deliberate trade of evolution for density, so it is opted
	// into rather than fallen into.
	Layout_LAYOUT_UNSPECIFIED Layout = 0
	// LAYOUT_TABLE is the evolvable, vtable-backed record. Always legal.
	Layout_LAYOUT_TABLE Layout = 1
	// LAYOUT_STRUCT is the packed, fixed-size record.
	//
	// A message is only eligible when every field is a fixed-width scalar, an
	// enum, or another struct: no strings, no bytes, no repeated fields, no maps,
	// no oneofs, and no message fields that are themselves tables. Asking for it
	// on a message that does not qualify is a build error naming the field that
	// disqualified it, rather than a silent downgrade — because the caller chose
	// LAYOUT_STRUCT for a memory-layout reason, and quietly giving them a table
	// would meet the schema's needs while missing the point.
	Layout_LAYOUT_STRUCT Layout = 2
)

// Enum value maps for Layout.
var (
	Layout_name = map[int32]string{
		0: "LAYOUT_UNSPECIFIED",
		1: "LAYOUT_TABLE",
		2: "LAYOUT_STRUCT",
	}
	Layout_value = map[string]int32{
		"LAYOUT_UNSPECIFIED": 0,
		"LAYOUT_TABLE":       1,
		"LAYOUT_STRUCT":      2,
	}
)

func (x Layout) Enum() *Layout {
	p := new(Layout)
	*p = x
	return p
}

func (x Layout) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Layout) Descriptor() protoreflect.EnumDescriptor {
	return file_buffers_v1_schema_proto_enumTypes[0].Descriptor()
}

func (Layout) Type() protoreflect.EnumType {
	return &file_buffers_v1_schema_proto_enumTypes[0]
}

func (x Layout) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Layout.Descriptor instead.
func (Layout) EnumDescriptor() ([]byte, []int) {
	return file_buffers_v1_schema_proto_rawDescGZIP(), []int{0}
}

// IntWidth names a concrete integer width, used where a target requires one and
// proto does not supply it.
//
// FlatBuffers enums carry an explicit underlying type; proto enums are always
// varint-encoded int32. Defaulting every generated enum to `int` wastes three
// bytes per value in a struct, which is exactly where it is least affordable.
type IntWidth int32

const (
	// INT_WIDTH_UNSPECIFIED defaults to INT_WIDTH_INT32, matching proto's own
	// encoding.
	IntWidth_INT_WIDTH_UNSPECIFIED IntWidth = 0
	// INT_WIDTH_INT8 is a signed byte, -128 to 127.
	IntWidth_INT_WIDTH_INT8 IntWidth = 1
	// INT_WIDTH_UINT8 is an unsigned byte, 0 to 255. The usual choice for a small
	// closed enum in a high-rate message.
	IntWidth_INT_WIDTH_UINT8 IntWidth = 2
	// INT_WIDTH_INT16 is a signed 16-bit integer.
	IntWidth_INT_WIDTH_INT16 IntWidth = 3
	// INT_WIDTH_UINT16 is an unsigned 16-bit integer.
	IntWidth_INT_WIDTH_UINT16 IntWidth = 4
	// INT_WIDTH_INT32 is a signed 32-bit integer, matching proto's own enum
	// encoding.
	IntWidth_INT_WIDTH_INT32 IntWidth = 5
	// INT_WIDTH_UINT32 is an unsigned 32-bit integer.
	IntWidth_INT_WIDTH_UINT32 IntWidth = 6
	// INT_WIDTH_INT64 is a signed 64-bit integer.
	IntWidth_INT_WIDTH_INT64 IntWidth = 7
	// INT_WIDTH_UINT64 is an unsigned 64-bit integer. Legal, and almost never what
	// an enum needs.
	IntWidth_INT_WIDTH_UINT64 IntWidth = 8
)

// Enum value maps for IntWidth.
var (
	IntWidth_name = map[int32]string{
		0: "INT_WIDTH_UNSPECIFIED",
		1: "INT_WIDTH_INT8",
		2: "INT_WIDTH_UINT8",
		3: "INT_WIDTH_INT16",
		4: "INT_WIDTH_UINT16",
		5: "INT_WIDTH_INT32",
		6: "INT_WIDTH_UINT32",
		7: "INT_WIDTH_INT64",
		8: "INT_WIDTH_UINT64",
	}
	IntWidth_value = map[string]int32{
		"INT_WIDTH_UNSPECIFIED": 0,
		"INT_WIDTH_INT8":        1,
		"INT_WIDTH_UINT8":       2,
		"INT_WIDTH_INT16":       3,
		"INT_WIDTH_UINT16":      4,
		"INT_WIDTH_INT32":       5,
		"INT_WIDTH_UINT32":      6,
		"INT_WIDTH_INT64":       7,
		"INT_WIDTH_UINT64":      8,
	}
)

func (x IntWidth) Enum() *IntWidth {
	p := new(IntWidth)
	*p = x
	return p
}

func (x IntWidth) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntWidth) Descriptor() protoreflect.EnumDescriptor {
	return file_buffers_v1_schema_proto_enumTypes[1].Descriptor()
}

func (IntWidth) Type() protoreflect.EnumType {
	return &file_buffers_v1_schema_proto_enumTypes[1]
}

func (x IntWidth) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntWidth.Descriptor instead.
func (IntWidth) EnumDescriptor() ([]byte, []int) {
	return file_buffers_v1_schema_proto_rawDescGZIP(), []int{1}
}

// FileOptions carries the per-file names each target needs and proto does not
// declare.
//
// Applied via:
//
//	option (buffers.v1.file) = {
//	  namespace: "sensors.v1"
//	  ros_package: "sensor_msgs"
//	  file_id: "SNSR"
//	};
type FileOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// namespace is the FlatBuffers `namespace` and the Cap'n Proto
	// `$Cxx.namespace`. Defaults to the proto package, which is already dotted.
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// capnp_id pins the file's Cap'n Proto 64-bit ID.
	//
	// Left unset, the plugin derives one deterministically from the proto file
	// path (see plugin/factory/bufir/capnpid.go) so that regenerating a schema
	// produces the same ID rather than the random one `capnp id` would mint. Set
	// it when adopting a .capnp file that already exists in the wild: its ID is
	// part of every consumer's build, and rederiving it would orphan them.
	//
	// Cap'n Proto requires the high bit set, so every valid ID read as a signed
	// integer is negative. That is the identity's bit pattern, not a quantity, and
	// the plugin renders it as `@0x%016x` of the same 64 bits.
	CapnpId int64 `protobuf:"varint,2,opt,name=capnp_id,json=capnpId,proto3" json:"capnp_id,omitempty"`
	// ros_package is the ROS 2 package the emitted .msg and .srv files belong to.
	// Defaults to the proto package's first segment with dots replaced by
	// underscores, which is the ROS naming rule.
	RosPackage string `protobuf:"bytes,3,opt,name=ros_package,json=rosPackage,proto3" json:"ros_package,omitempty"`
	// jvm_package is the Kotlin or Java package Square Wire generates into.
	// Defaults to the file's `java_package` when it declares one, then to the
	// proto package.
	JvmPackage string `protobuf:"bytes,4,opt,name=jvm_package,json=jvmPackage,proto3" json:"jvm_package,omitempty"`
	// file_id is the FlatBuffers `file_identifier`: a 4-character magic string
	// stamped into the buffer so a reader can reject a payload that is not the
	// schema it expected. Exactly 4 ASCII characters, or empty for none.
	FileId string `protobuf:"bytes,5,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	// file_extension is the FlatBuffers `file_extension` used for binary payloads
	// written by the generated code, for example "bin".
	FileExtension string `protobuf:"bytes,6,opt,name=file_extension,json=fileExtension,proto3" json:"file_extension,omitempty"`
	// fbs_include adds `include` lines to the emitted .fbs beyond the ones derived
	// from the proto's own imports. An escape hatch for hand-written schema that
	// the generated file must compose with.
	FbsInclude    []string `protobuf:"bytes,7,rep,name=fbs_include,json=fbsInclude,proto3" json:"fbs_include,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileOptions) Reset() {
	*x = FileOptions{}
	mi := &file_buffers_v1_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOptions) ProtoMessage() {}

func (x *FileOptions) ProtoReflect() protoreflect.Message {
	mi := &file_buffers_v1_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOptions.ProtoReflect.Descriptor instead.
func (*FileOptions) Descriptor() ([]byte, []int) {
	return file_buffers_v1_schema_proto_rawDescGZIP(), []int{0}
}

func (x *FileOptions) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *FileOptions) GetCapnpId() int64 {
	if x != nil {
		return x.CapnpId
	}
	return 0
}

func (x *FileOptions) GetRosPackage() string {
	if x != nil {
		return x.RosPackage
	}
	return ""
}

func (x *FileOptions) GetJvmPackage() string {
	if x != nil {
		return x.JvmPackage
	}
	return ""
}

func (x *FileOptions) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileOptions) GetFileExtension() string {
	if x != nil {
		return x.FileExtension
	}
	return ""
}

func (x *FileOptions) GetFbsInclude() []string {
	if x != nil {
		return x.FbsInclude
	}
	return nil
}

// MessageOptions shapes how one message lands in each target.
type MessageOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// skip excludes the message from every target. A message reachable only from a
	// skipped message is not itself skipped: reachability is not a policy, and
	// silently dropping a type someone else imports is worse than emitting an
	// unused one.
	Skip bool `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	// layout selects the FlatBuffers table or struct distinction. See Layout.
	Layout Layout `protobuf:"varint,2,opt,name=layout,proto3,enum=buffers.v1.Layout" json:"layout,omitempty"`
	// capnp_id pins this type's Cap'n Proto ID, for the same adoption reason
	// FileOptions.capnp_id exists. Derived from the file ID and the type's fully
	// qualified name when unset.
	CapnpId int64 `protobuf:"varint,3,opt,name=capnp_id,json=capnpId,proto3" json:"capnp_id,omitempty"`
	// targets restricts the message to the named targets: "flatbuffers", "capnp",
	// "ros", or "wire". Empty means every target, which is the norm; a non-empty
	// list is how a message that only makes sense over one wire — a ROS-only
	// diagnostic record, say — stays out of the others.
	Targets []string `protobuf:"bytes,4,rep,name=targets,proto3" json:"targets,omitempty"`
	// ros_type overrides the ROS type name, which is otherwise the proto message
	// name. ROS requires one message per file named after the type, so this
	// renames the emitted file too.
	RosType string `protobuf:"bytes,5,opt,name=ros_type,json=rosType,proto3" json:"ros_type,omitempty"`
	// fbs_original_order emits FlatBuffers' `(original_order)` attribute, which
	// stops flatc reordering a table's fields by size for packing.
	//
	// It is rarely needed here, because this plugin assigns every field an
	// explicit `id:` and explicit ids already fix the vtable slots. It matters
	// when the emitted schema is hand-edited afterwards to drop those ids.
	FbsOriginalOrder bool `protobuf:"varint,6,opt,name=fbs_original_order,json=fbsOriginalOrder,proto3" json:"fbs_original_order,omitempty"`
	// fbs_root marks this message as the emitted .fbs file's `root_type`.
	//
	// FlatBuffers allows one root per schema file, and it is what `GetRootAsX`
	// is generated for. Nothing in a .proto identifies it: a file typically holds
	// several messages and proto has no notion of which one is the payload rather
	// than a part of it, so it has to be said here.
	//
	// Setting `file_id` without marking a root is a diagnostic, because a
	// FlatBuffers `file_identifier` is only legal alongside a `root_type` — flatc
	// rejects the pair, and finding that out from flatc rather than from here costs
	// a round trip through a toolchain the plugin may not have run.
	//
	// At most one message per file may set it.
	FbsRoot       bool `protobuf:"varint,7,opt,name=fbs_root,json=fbsRoot,proto3" json:"fbs_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	mi := &file_buffers_v1_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_buffers_v1_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOptions.ProtoReflect.Descriptor instead.
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return file_buffers_v1_schema_proto_rawDescGZIP(), []int{1}
}

func (x *MessageOptions) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *MessageOptions) GetLayout() Layout {
	if x != nil {
		return x.Layout
	}
	return Layout_LAYOUT_UNSPECIFIED
}

func (x *MessageOptions) GetCapnpId() int64 {
	if x != nil {
		return x.CapnpId
	}
	return 0
}

func (x *MessageOptions) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *MessageOptions) GetRosType() string {
	if x != nil {
		return x.RosType
	}
	return ""
}

func (x *MessageOptions) GetFbsOriginalOrder() bool {
	if x != nil {
		return x.FbsOriginalOrder
	}
	return false
}

func (x *MessageOptions) GetFbsRoot() bool {
	if x != nil {
		return x.FbsRoot
	}
	return false
}

// FieldOptions shapes how one field lands in each target.
type FieldOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// skip excludes the field from every target.
	//
	// On a serialization schema this is a sharper instrument than it looks: a
	// skipped field is not merely absent from the generated code, it permanently
	// consumes its ordinal, because a later run that unskips it must land on the
	// same slot. The plugin records skipped fields in buffers.lock for that
	// reason.
	Skip bool `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	// ordinal pins the field's target slot: the FlatBuffers `id:` attribute and
	// the Cap'n Proto `@N`.
	//
	// Leave it unset. The plugin derives a stable ordinal from the proto field
	// number (see plugin/factory/bufir/ordinal.go), and a derived ordinal that
	// never moves is worth more than a hand-written one that can be typo'd into
	// aliasing another field. Set it only to adopt an existing .capnp or .fbs
	// whose slots were assigned before this plugin existed — which is precisely
	// the case the derivation cannot reconstruct.
	//
	// Ordinals are 0-based, matching both target formats and unlike proto field
	// numbers, which start at 1.
	Ordinal int32 `protobuf:"varint,2,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	// key marks the field as the FlatBuffers `(key)`: the one field a vector of
	// this table may be sorted by and binary-searched on. At most one per table.
	Key bool `protobuf:"varint,3,opt,name=key,proto3" json:"key,omitempty"`
	// shared emits FlatBuffers' `(shared)` on a string field, so identical values
	// are written once and referenced twice. Worth it for a repeated enum-like
	// string; wasted on a field whose values are all distinct.
	Shared bool `protobuf:"varint,4,opt,name=shared,proto3" json:"shared,omitempty"`
	// max_len bounds a repeated field or string for ROS, emitting `T[<=N]` or
	// `string<=N`. ROS bounds are part of the type, and an unbounded sequence in a
	// real-time message is the kind of thing a reviewer is looking for.
	//
	// Ignored by targets whose types carry no bound.
	MaxLen int32 `protobuf:"varint,5,opt,name=max_len,json=maxLen,proto3" json:"max_len,omitempty"`
	// fixed_len makes a repeated field a ROS fixed-size array, `T[N]`, and a
	// FlatBuffers fixed-size array inside a struct.
	//
	// The proto side stays `repeated`, because proto cannot express a length. That
	// makes this a claim the producer must uphold rather than one the schema
	// enforces, and the generated doc comment says so on every affected field.
	FixedLen int32 `protobuf:"varint,6,opt,name=fixed_len,json=fixedLen,proto3" json:"fixed_len,omitempty"`
	// ros_default is a literal default value for the ROS field, emitted after the
	// field name. ROS defaults are a message-definition feature with no proto
	// equivalent, since proto3 has no field defaults.
	RosDefault string `protobuf:"bytes,7,opt,name=ros_default,json=rosDefault,proto3" json:"ros_default,omitempty"`
	// capnp_group folds this field, with every other field naming the same group,
	// into a Cap'n Proto `group`. Groups cost nothing on the wire — they are
	// presentation over the same slots — and are how a flat proto message with an
	// obvious internal grouping reads well in Cap'n Proto without changing layout.
	CapnpGroup string `protobuf:"bytes,8,opt,name=capnp_group,json=capnpGroup,proto3" json:"capnp_group,omitempty"`
	// targets restricts the field to the named targets. See
	// buffers.v1.MessageOptions.targets.
	Targets       []string `protobuf:"bytes,9,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_buffers_v1_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_buffers_v1_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_buffers_v1_schema_proto_rawDescGZIP(), []int{2}
}

func (x *FieldOptions) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *FieldOptions) GetOrdinal() int32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *FieldOptions) GetKey() bool {
	if x != nil {
		return x.Key
	}
	return false
}

func (x *FieldOptions) GetShared() bool {
	if x != nil {
		return x.Shared
	}
	return false
}

func (x *FieldOptions) GetMaxLen() int32 {
	if x != nil {
		return x.MaxLen
	}
	return 0
}

func (x *FieldOptions) GetFixedLen() int32 {
	if x != nil {
		return x.FixedLen
	}
	return 0
}

func (x *FieldOptions) GetRosDefault() string {
	if x != nil {
		return x.RosDefault
	}
	return ""
}

func (x *FieldOptions) GetCapnpGroup() string {
	if x != nil {
		return x.CapnpGroup
	}
	return ""
}

func (x *FieldOptions) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

// EnumOptions shapes how one enum lands in each target.
type EnumOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// skip excludes the enum from every target.
	Skip bool `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	// underlying is the FlatBuffers enum's underlying integer type. Defaults to
	// INT_WIDTH_INT32, matching proto's own encoding; narrow it where the values
	// fit and the density matters.
	//
	// The plugin rejects a width that cannot hold every declared value, rather
	// than truncating.
	Underlying IntWidth `protobuf:"varint,2,opt,name=underlying,proto3,enum=buffers.v1.IntWidth" json:"underlying,omitempty"`
	// bit_flags emits FlatBuffers' `(bit_flags)`, turning the enum into a bitmask
	// whose declared values are bit positions rather than values.
	//
	// AIP-126 requires a zero `_UNSPECIFIED` value, and a bit_flags enum cannot
	// have one — position 0 is a real bit. The plugin drops the unspecified value
	// for this enum only, and says so in a diagnostic, because silently keeping it
	// would make bit 0 mean "unspecified" for every consumer.
	BitFlags      bool `protobuf:"varint,3,opt,name=bit_flags,json=bitFlags,proto3" json:"bit_flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumOptions) Reset() {
	*x = EnumOptions{}
	mi := &file_buffers_v1_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumOptions) ProtoMessage() {}

func (x *EnumOptions) ProtoReflect() protoreflect.Message {
	mi := &file_buffers_v1_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumOptions.ProtoReflect.Descriptor instead.
func (*EnumOptions) Descriptor() ([]byte, []int) {
	return file_buffers_v1_schema_proto_rawDescGZIP(), []int{3}
}

func (x *EnumOptions) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *EnumOptions) GetUnderlying() IntWidth {
	if x != nil {
		return x.Underlying
	}
	return IntWidth_INT_WIDTH_UNSPECIFIED
}

func (x *EnumOptions) GetBitFlags() bool {
	if x != nil {
		return x.BitFlags
	}
	return false
}

// EnumValueOptions pins one enumerant's slot.
type EnumValueOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ordinal pins the Cap'n Proto enumerant ordinal, which is 0-based and
	// contiguous — unlike a proto enum's value numbers, which are neither.
	//
	// As with buffers.v1.FieldOptions.ordinal: leave it unset unless adopting an
	// existing schema.
	Ordinal int32 `protobuf:"varint,1,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	// skip excludes the value. It permanently consumes its ordinal, for the same
	// reason buffers.v1.FieldOptions.skip does.
	Skip          bool `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumValueOptions) Reset() {
	*x = EnumValueOptions{}
	mi := &file_buffers_v1_schema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumValueOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumValueOptions) ProtoMessage() {}

func (x *EnumValueOptions) ProtoReflect() protoreflect.Message {
	mi := &file_buffers_v1_schema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumValueOptions.ProtoReflect.Descriptor instead.
func (*EnumValueOptions) Descriptor() ([]byte, []int) {
	return file_buffers_v1_schema_proto_rawDescGZIP(), []int{4}
}

func (x *EnumValueOptions) GetOrdinal() int32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *EnumValueOptions) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

// OneofOptions shapes how a proto oneof lands where the target has a union.
type OneofOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// union_type names the generated FlatBuffers union type, which unlike Cap'n
	// Proto's anonymous unions must be a named top-level type. Defaults to the
	// message name followed by the PascalCase oneof name, for example
	// `ReadingPayload`.
	UnionType string `protobuf:"bytes,1,opt,name=union_type,json=unionType,proto3" json:"union_type,omitempty"`
	// skip excludes the oneof and every field in it.
	Skip          bool `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneofOptions) Reset() {
	*x = OneofOptions{}
	mi := &file_buffers_v1_schema_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneofOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofOptions) ProtoMessage() {}

func (x *OneofOptions) ProtoReflect() protoreflect.Message {
	mi := &file_buffers_v1_schema_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofOptions.ProtoReflect.Descriptor instead.
func (*OneofOptions) Descriptor() ([]byte, []int) {
	return file_buffers_v1_schema_proto_rawDescGZIP(), []int{5}
}

func (x *OneofOptions) GetUnionType() string {
	if x != nil {
		return x.UnionType
	}
	return ""
}

func (x *OneofOptions) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

var File_buffers_v1_schema_proto protoreflect.FileDescriptor

const file_buffers_v1_schema_proto_rawDesc = "" +
	"\n" +
	"\x17buffers/v1/schema.proto\x12\n" +
	"buffers.v1\"\xe9\x01\n" +
	"\vFileOptions\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x19\n" +
	"\bcapnp_id\x18\x02 \x01(\x03R\acapnpId\x12\x1f\n" +
	"\vros_package\x18\x03 \x01(\tR\n" +
	"rosPackage\x12\x1f\n" +
	"\vjvm_package\x18\x04 \x01(\tR\n" +
	"jvmPackage\x12\x17\n" +
	"\afile_id\x18\x05 \x01(\tR\x06fileId\x12%\n" +
	"\x0efile_extension\x18\x06 \x01(\tR\rfileExtension\x12\x1f\n" +
	"\vfbs_include\x18\a \x03(\tR\n" +
	"fbsInclude\"\xe9\x01\n" +
	"\x0eMessageOptions\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\bR\x04skip\x12*\n" +
	"\x06layout\x18\x02 \x01(\x0e2\x12.buffers.v1.LayoutR\x06layout\x12\x19\n" +
	"\bcapnp_id\x18\x03 \x01(\x03R\acapnpId\x12\x18\n" +
	"\atargets\x18\x04 \x03(\tR\atargets\x12\x19\n" +
	"\bros_type\x18\x05 \x01(\tR\arosType\x12,\n" +
	"\x12fbs_original_order\x18\x06 \x01(\bR\x10fbsOriginalOrder\x12\x19\n" +
	"\bfbs_root\x18\a \x01(\bR\afbsRoot\"\xf8\x01\n" +
	"\fFieldOptions\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\bR\x04skip\x12\x18\n" +
	"\aordinal\x18\x02 \x01(\x05R\aordinal\x12\x10\n" +
	"\x03key\x18\x03 \x01(\bR\x03key\x12\x16\n" +
	"\x06shared\x18\x04 \x01(\bR\x06shared\x12\x17\n" +
	"\amax_len\x18\x05 \x01(\x05R\x06maxLen\x12\x1b\n" +
	"\tfixed_len\x18\x06 \x01(\x05R\bfixedLen\x12\x1f\n" +
	"\vros_default\x18\a \x01(\tR\n" +
	"rosDefault\x12\x1f\n" +
	"\vcapnp_group\x18\b \x01(\tR\n" +
	"capnpGroup\x12\x18\n" +
	"\atargets\x18\t \x03(\tR\atargets\"t\n" +
	"\vEnumOptions\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\bR\x04skip\x124\n" +
	"\n" +
	"underlying\x18\x02 \x01(\x0e2\x14.buffers.v1.IntWidthR\n" +
	"underlying\x12\x1b\n" +
	"\tbit_flags\x18\x03 \x01(\bR\bbitFlags\"@\n" +
	"\x10EnumValueOptions\x12\x18\n" +
	"\aordinal\x18\x01 \x01(\x05R\aordinal\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\bR\x04skip\"A\n" +
	"\fOneofOptions\x12\x1d\n" +
	"\n" +
	"union_type\x18\x01 \x01(\tR\tunionType\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\bR\x04skip*E\n" +
	"\x06Layout\x12\x16\n" +
	"\x12LAYOUT_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fLAYOUT_TABLE\x10\x01\x12\x11\n" +
	"\rLAYOUT_STRUCT\x10\x02*\xcf\x01\n" +
	"\bIntWidth\x12\x19\n" +
	"\x15INT_WIDTH_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eINT_WIDTH_INT8\x10\x01\x12\x13\n" +
	"\x0fINT_WIDTH_UINT8\x10\x02\x12\x13\n" +
	"\x0fINT_WIDTH_INT16\x10\x03\x12\x14\n" +
	"\x10INT_WIDTH_UINT16\x10\x04\x12\x13\n" +
	"\x0fINT_WIDTH_INT32\x10\x05\x12\x14\n" +
	"\x10INT_WIDTH_UINT32\x10\x06\x12\x13\n" +
	"\x0fINT_WIDTH_INT64\x10\a\x12\x14\n" +
	"\x10INT_WIDTH_UINT64\x10\bBj\n" +
	"\x0ecom.buffers.v1B\vSchemaProtoP\x01ZIgithub.com/the-protobuf-project/buffers/plugin/pb/bufferspbv1;bufferspbv1b\x06proto3"

var (
	file_buffers_v1_schema_proto_rawDescOnce sync.Once
	file_buffers_v1_schema_proto_rawDescData []byte
)

func file_buffers_v1_schema_proto_rawDescGZIP() []byte {
	file_buffers_v1_schema_proto_rawDescOnce.Do(func() {
		file_buffers_v1_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_buffers_v1_schema_proto_rawDesc), len(file_buffers_v1_schema_proto_rawDesc)))
	})
	return file_buffers_v1_schema_proto_rawDescData
}

var file_buffers_v1_schema_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_buffers_v1_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_buffers_v1_schema_proto_goTypes = []any{
	(Layout)(0),              // 0: buffers.v1.Layout
	(IntWidth)(0),            // 1: buffers.v1.IntWidth
	(*FileOptions)(nil),      // 2: buffers.v1.FileOptions
	(*MessageOptions)(nil),   // 3: buffers.v1.MessageOptions
	(*FieldOptions)(nil),     // 4: buffers.v1.FieldOptions
	(*EnumOptions)(nil),      // 5: buffers.v1.EnumOptions
	(*EnumValueOptions)(nil), // 6: buffers.v1.EnumValueOptions
	(*OneofOptions)(nil),     // 7: buffers.v1.OneofOptions
}
var file_buffers_v1_schema_proto_depIdxs = []int32{
	0, // 0: buffers.v1.MessageOptions.layout:type_name -> buffers.v1.Layout
	1, // 1: buffers.v1.EnumOptions.underlying:type_name -> buffers.v1.IntWidth
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_buffers_v1_schema_proto_init() }
func file_buffers_v1_schema_proto_init() {
	if File_buffers_v1_schema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_buffers_v1_schema_proto_rawDesc), len(file_buffers_v1_schema_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_buffers_v1_schema_proto_goTypes,
		DependencyIndexes: file_buffers_v1_schema_proto_depIdxs,
		EnumInfos:         file_buffers_v1_schema_proto_enumTypes,
		MessageInfos:      file_buffers_v1_schema_proto_msgTypes,
	}.Build()
	File_buffers_v1_schema_proto = out.File
	file_buffers_v1_schema_proto_goTypes = nil
	file_buffers_v1_schema_proto_depIdxs = nil
}
