// Code generated by protoc-gen-protokit. DO NOT EDIT.
// versions:
// 	protoc-gen-protokit test
// 	protoc test
// source: (every file in this run)
//
// target: wire
// field slots below are recorded in buffers.lock; edit the .proto, not this file
//
// protokit — https://github.com/the-protobuf-project/protokit
// This is a fragment, not a build file: paste the block below into your
// build.gradle.kts, or keep it here and read it as the record of which types
// are API roots.
//
// It is not written as an `apply(from = ...)` script because the Kotlin DSL
// cannot configure a typed plugin extension from an applied script without
// resolving the plugin's types by hand, which is worse to read than a paste.
//
// Wire consumes the .proto files directly. There is no generated schema to
// point at, and `sourcePath` below should name wherever your protos already
// live.

wire {
  sourcePath {
    srcDir("src/main/proto")
  }

  // Tree-shaking roots, derived from AIP rather than chosen by hand.
  //
  // An API's reachable surface is exactly its services plus its resources:
  // everything a caller can invoke hangs off a method, and everything a
  // resource carries hangs off the resource. Wire closes over these
  // transitively and prunes the rest, so a JVM app stops paying for
  // messages it never touches.
  roots(
    "sensors.v1.Reading", // AIP-123 resource sensors.example.com/Reading
    "sensors.v1.Robot", // AIP-123 resource sensors.example.com/Robot
    "sensors.v1.Sensor", // AIP-123 resource sensors.example.com/Sensor
    "sensors.v1.SensorService", // service
    "sensors.v1.StreamReadingsResponse", // payload of topic "sensor_readings"
  )

  kotlin {
    // suspending is the call style for a coroutine codebase; use
    // "blocking" if the callers are not suspend functions.
    rpcCallStyle = "suspending"
    rpcRole = "client"
    javaInterop = false
  }
}

// JVM packages the generated code will land in, one per proto package.
// Taken from (buffers.v1.file).jvm_package, then java_package, then the proto
// package — the same order Wire itself resolves them in, recorded here so a
// reviewer can see the result without running the build.
//   sensors.v1 -> com.sensors.v1
