// Code generated by protoc-gen-protokit. DO NOT EDIT.
// versions:
// 	protoc-gen-protokit test
// 	protoc test
// source: (every service in this run)
//
// target: wire
// field slots below are recorded in buffers.lock; edit the .proto, not this file
//
// protokit — https://github.com/the-protobuf-project/protokit
package com.sensors.v1

/**
 * Topics published by the services in this schema.
 *
 * The binding between a topic name and the message carried on it exists nowhere
 * in the generated protobuf types, so subscribing otherwise means retyping a
 * string literal that nothing checks. [type] is the message a subscriber should
 * decode with.
 */
object Topics {
  /** StreamReadings publishes every reading a sensor produces. Carries [com.sensors.v1.StreamReadingsResponse]. */
  const val STREAM_READINGS: String = "sensor_readings"
}
