package main

// compile.go drives the external toolchains over the schema a run just emitted.
//
// One invocation per source directory rather than one for everything: the output
// path and the package flags both vary per directory, and the generators take
// them globally.

import (
	"fmt"
	"path"
	"sort"

	"github.com/spf13/cobra"

	"github.com/the-protobuf-project/protokit/buffers"

	"github.com/the-protobuf-project/buffers/plugin/factory/config"
	"github.com/the-protobuf-project/buffers/plugin/factory/coreir"
	"github.com/the-protobuf-project/buffers/plugin/factory/target/langs"
)

// compile drives the external toolchains for every entry that asked for a
// language.
func compile(cmd *cobra.Command, cfg *config.Config, entries []config.Entry, override string, model *coreir.Model) error {
	for _, e := range entries {
		languages := e.Languages
		if override != "" {
			languages = []string{override}
		}
		if len(languages) == 0 {
			continue
		}

		ext := langs.Extension(e.Target)
		if ext == "" {
			// ros and wire have no one-shot compiler; their code generation is
			// driven by colcon and Gradle. Saying so once is better than failing.
			fmt.Fprintf(cmd.OutOrStdout(),
				"%-12s   schema only — %s code is generated by the consuming build, not by a standalone compiler\n",
				e.Target, e.Target)
			continue
		}

		dir := cfg.OutDir(e)
		files, err := langs.SchemaFiles(dir, ext)
		if err != nil {
			return err
		}
		if len(files) == 0 {
			continue
		}

		groups := schemaGroups(model, files, ext, cfg.ModuleFor(e))
		warnUnreconcilableJVM(cmd, groups, languages)
		warnOldFlatcForGo(cmd, e, languages)
		warnCapnpTypeScript(cmd, e, groups, languages)

		for _, l := range languages {
			// Some languages consume the emitted schema directly and have no
			// generator to run — see langs/runtimeloaded.go. Saying so is the
			// whole job; there is nothing to invoke.
			if note, ok := langs.RuntimeLoaded(e.Target, l); ok {
				fmt.Fprintf(cmd.OutOrStdout(), "%-12s   %s (%s)\n", e.Target, note, l)
				continue
			}

			out := cfg.LangDir(e, l)
			// One invocation per source directory rather than one for everything:
			// the output path and the package flags both vary per directory, and
			// the generators take them globally. See langs/layout.go.
			for _, req := range langs.Plan(e.Target, l, dir, out, groups) {
				// Every language this entry emits, not just the current one: the
				// schema on disk carries the annotation blocks for all of them,
				// and an unresolvable annotation import fails the parse whatever
				// language is being generated.
				req.Annotated = languages

				// flatc names one file per generated type, in PascalCase, where Go
				// wants lowercase snake_case. A Go file name means nothing to the
				// compiler, so the fix is a rename — staged through a scratch
				// directory so a rerun replaces last run's files instead of
				// accumulating beside them. See langs/gofiles.go for why this
				// cannot be a flatc flag and for the build-constraint hazard a
				// naive rename introduces.
				if langs.GoFilesNeedRenaming(e.Target, l) {
					if _, err := langs.RunWithGoRename(req); err != nil {
						return err
					}
					continue
				}
				if err := langs.Run(req); err != nil {
					return err
				}
			}
			fmt.Fprintf(cmd.OutOrStdout(), "%-12s -> %s (%s)\n", e.Target, out, l)
		}
	}
	return nil
}

// schemaGroups buckets emitted schema files by source directory and attaches the
// package names the proto declared for that directory.
//
// The mapping back to the proto is by path: a schema at sensors/v1/sensors.fbs
// came from sensors/v1/sensors.proto, so the .proto's java_package and go_package
// are the ones its generated code should declare. Files the plugin synthesized —
// the well-known-type prelude — match no proto and fall through with only the
// namespace flatc derives, which is correct: they are this plugin's own types.
func schemaGroups(model *coreir.Model, files []string, ext, goModule string) []langs.Group {
	byDir := langs.GroupFiles(files)

	// Index the proto files by the directory their schema lands in.
	meta := map[string]*buffers.File{}
	if model != nil && model.Schema != nil {
		for _, f := range model.Schema.Files {
			dir := path.Dir(f.Path)
			if dir == "." {
				dir = ""
			}
			meta[dir] = f
		}
	}

	dirs := make([]string, 0, len(byDir))
	for dir := range byDir {
		dirs = append(dirs, dir)
	}
	sort.Strings(dirs)

	out := make([]langs.Group, 0, len(dirs))
	for _, dir := range dirs {
		g := langs.Group{Dir: dir, Files: byDir[dir], GoModule: goModule}
		if f, ok := meta[dir]; ok {
			g.Namespace = f.Namespace
			g.JVMPackage = f.JVMPackage
			g.GoPackage = f.GoPackage
		}
		out = append(out, g)
	}
	return out
}
