# Code generated by protoc-gen-protokit. DO NOT EDIT.
# versions:
# 	protoc-gen-protokit test
# 	protoc test
# source: buffers/wellknown.thrift
#
# target: thrift
# field ids are the proto field numbers; Thrift numbers fields the way proto does
#
# protokit — https://github.com/the-protobuf-project/protokit
namespace * buffers.wellknown
namespace java com.buffers.wellknown
namespace go wellknown

/**
 * Timestamp is google.protobuf.Timestamp: seconds since the Unix epoch plus a
 * nanosecond adjustment.
 */
struct Timestamp {
  1: i64 seconds
  2: i32 nanos
}
