// Package provenance renders the "Code generated by" banner every emitted file
// carries.
//
// It exists as its own package for one reason: the banner has to be
// byte-identical across runs, and the comment syntax has to differ per target.
// FlatBuffers and Gradle take "//", Cap'n Proto and ROS take "#". Leaving each
// target to assemble its own would give four banners that drift, and a golden
// test that fails on whichever one was edited last.
package provenance

import "github.com/the-protobuf-project/protokit/header"

// Comment is a target's line-comment marker.
type Comment string

const (
	// Slash is the marker for FlatBuffers and Gradle.
	Slash Comment = "//"
	// Hash is the marker for Cap'n Proto and ROS message definitions.
	Hash Comment = "#"
)

// Info is what a banner says about where a file came from.
type Info struct {
	// Version is the plugin build version. Empty renders as "(unknown)", which is
	// what a `go build` of a working tree honestly is.
	Version string

	// ProtocVersion is the compiler that produced the descriptors.
	ProtocVersion string

	// Source is the originating .proto path.
	Source string

	// Target names the backend that rendered the file, so a reader who finds a
	// stray .fbs knows which half of the config produced it.
	Target string

	// Notes are extra context lines, shown before the project link.
	Notes []string
}

// Render returns the banner, comment-prefixed and newline-terminated.
//
// The heavy lifting is protokit's header package, which already opens with
// "Code generated by … DO NOT EDIT." — so this adds only the facts protokit's
// Info has no field for, and deliberately does not restate the warning. An
// earlier version emitted its own DO-NOT-EDIT line above protokit's and every
// generated file said it twice.
func Render(c Comment, in Info) string {
	notes := in.Notes
	if in.Target != "" {
		notes = append([]string{"target: " + in.Target}, notes...)
	}
	// The ledger note goes in every file because it is the non-obvious half of
	// "do not edit": the ordinals below are not free-floating, and hand-editing
	// one desynchronizes it from buffers.lock without any error surfacing.
	notes = append(notes, "field slots below are recorded in "+LedgerName+"; edit the .proto, not this file")

	return header.Render(string(c), header.Info{
		PluginVersion: in.Version,
		ProtocVersion: in.ProtocVersion,
		Source:        in.Source,
		Notes:         notes,
	})
}

// LedgerName is the ordinal ledger's conventional file name, named here so the
// banner and the plugin agree without provenance importing bufir.
const LedgerName = "buffers.lock"
